services:
  postgres:
    container_name: music_academy
    image: postgres:15.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: .
    container_name: testapp_container
    ports:
        - 8080:8080
    environment:
      db-url: jdbc:postgresql://postgres:5432/music
      db-username: postgres
      db-password: postgres
      spring.security.secret.key: 25432A462D4A614E645267556B58703273357638792F413F4428472B4B625065
      accessKey: you_access_key
      secret: your_secret_key
      bucketName: your_bucket_name
      region: your_bucket_region us-east-1

    depends_on:
      - postgres
    restart: unless-stopped
