services:
  postgres:
    container_name: music_academy
    image: postgres:15.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: .
    container_name: testapp_container
    ports:
        - 8080:8080
    environment:
      db-url: jdbc:postgresql://postgres:5432/music
      db-username: postgres
      db-password: postgres
      accessKey: AKIAU3ABYX5ZSMG5RAOO
      secret: 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
      bucketName: musicspring
      region: us-east-1
    depends_on:
      - postgres
    restart: unless-stopped
